#!/usr/bin/env bash
# Script to audit subdomain DNS records

# Function to get DNS record
get_record_info() {
  local full_domain="$1"
  dig "$full_domain" +short | awk -v subdomain_name="$full_domain" 'NR==1 {
    if ($0 ~ /^[0-9.]+$/) {
      print "The subdomain " subdomain_name " is a A record and points to " $0
    } else {
      print "The subdomain " subdomain_name " is not an A record or has no DNS entry"
    }
  }'
}

# Main logic
domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
  for sub in www lb-01 web-01 web-02
  do
    get_record_info "$sub.$domain"
  done
else
  get_record_info "$subdomain.$domain"
fi
