#!/usr/bin/env bash
# Configure UFW to allow only ports 22, 80, 443 and block the rest

apt-get update
apt-get install ufw -y

ufw default deny incoming
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw --force enable
